import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import About from '../components/About';
import Development from '../components/Development';
import Main from '../components/Main';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Jesus app</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div
				style={{
					backgroundImage:
						'https://images.unsplash.com/photo-1571771019784-3ff35f4f4277?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=800&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ',
				}}
				className='back-fixed'></div>
			<section className='h:bg-[#111] w-screen h-screen'>
				<Main />
			</section>
			<About />
			<div className='relative'>
				<Development />
			</div>

			<button>
				<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
			</button>
		</div>
	);
};

export default Home;
