import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import About from '../components/About';
import Development from '../components/Development';
import Main from '../components/Main';
import Projects from '../components/Projects';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Jesus app</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<section id='main' className='h:bg-[#111]'>
				<Main />
			</section>
			<section id='project' className='relative'>
				<Projects />
			</section>
			<section id='about'>
				<About />
			</section>
			{/* <section id='dev' className='relative'>
				<Development />
			</section> */}
		</div>
	);
};

export default Home;
