import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';

const Home: NextPage = () => {
	return (
		<div className='bg-keyboard-img h-screen w-screen  bg-no-repeat bg-cover bg-center'>
			<Head>
				<title>Jesus app</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />

			<main>
				<h1>
					Welcome to <a href='#'>My Page</a>
				</h1>
			</main>

			<button>
				<Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
			</button>
		</div>
	);
};

export default Home;
